const data = [
  {
    id: 1,
    name: "Whey zero(com lactase)",
    description: "Black Skull-900g",
    price: 349.9,
    sale: false,
    flavor: "chocolate",
    categorie: "suplements",
  },
  {
    id: 2,
    name: "Whey zero(com lactose)",
    description: "Black Skull-900g",
    price: 349.9,
    sale: true,
    flavor: "baunilha",
    categorie: "suplements",
  },
  {
    id: 3,
    name: "Whey zero(com lactose)",
    description: "Black Skull-900g",
    price: 349.9,
    sale: false,
    size: "large",
    categorie: "clothing",
    color: "red",
  },
  {
    id: 4,
    name: "Whey zero(com lactose)",
    description: "Black Skull-900g",
    price: 349.9,
    sale: false,
    size: "medium",
    categorie: "clothing",
    color: "blue",
  },
  {
    id: 5,
    name: "Whey zero(com lactose)",
    description: "Black Skull-900g",
    price: 349.9,
    sale: true,
    flavor: "toffee",
    categorie: "suplements",
  },
  {
    id: 6,
    name: "Whey zero(com lactose)",
    description: "Black Skull-900g",
    price: 349.9,
    sale: true,
    size: "extra large",
    categorie: "clothing",
    color: "green",
  },
  {
    id: 7,
    name: "Whey zero(com lactose)",
    description: "Black Skull-900g",
    price: 349.9,
    sale: false,
    flavor: "morango",
    categorie: "suplements",
  },
  {
    id: 8,
    name: "Whey zero(com lactose)",
    description: "Black Skull-800g",
    price: 349.9,
    sale: true,
    flavor: "chocolate",
    categorie: "suplements",
  },
];
